allowBuilds:
  node-av: set this to true or false
  zeromq: set this to true or false

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@discordjs/opus'
  - '@seydx/node-av-win32-x64-mingw'
  - esbuild
  - sharp
  - zeromq

minimumReleaseAgeExclude:
  - '@lng2004/discord.js-selfbot-v13@3.7.2'

onlyBuiltDependencies:
  - '@lng2004/node-datachannel'
  - '@seydx/node-av-win32-x64-msvc'
  - node-av
